services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    volumes:
      - ./web:/app
      - ./logs:/app/logs
    depends_on:
      - db
    environment:
      - SECURE_COOKIES=False

  db:
    build: ./db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
